# Generated by Django 5.1.1 on 2025-05-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="type_role",
            field=models.CharField(
                choices=[("USER", "User"), ("ADMIN", "Admin")],
                default="TEXT",
                max_length=20,
            ),
        ),
    ]
