# Generated by Django 5.1.1 on 2025-06-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="media",
            field=models.URLField(blank=True, null=True),
        ),
    ]
