# Generated by Django 5.1.1 on 2025-05-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_type_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="type_role",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("USER", "User"), ("ADMIN", "Admin")],
                default="USER",
                max_length=20,
            ),
        ),
    ]
