# Generated by Django 5.1.1 on 2025-06-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_friendrequest_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="url_avatar",
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
