# Generated by Django 5.1.1 on 2025-06-11 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_post_media"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="update_at",
            new_name="updated_at",
        ),
        migrations.AlterField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="core.conversation",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="type_message",
            field=models.CharField(
                choices=[("text", "Text"), ("image", "Image"), ("video", "Video")],
                default="text",
                max_length=10,
            ),
        ),
    ]
