# Generated by Django 5.1.1 on 2025-06-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_update_at_message_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="media",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
