# Generated by Django 5.1.1 on 2025-06-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_post_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="media",
            field=models.ImageField(blank=True, null=True, upload_to="post_media/"),
        ),
    ]
