# Generated by Django 5.1.1 on 2025-06-12 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_post_media"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="media",
        ),
    ]
