# Generated by Django 5.1.1 on 2025-06-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_postmedia"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["user"], name="core_post_user_id_0cf6f1_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["number_emotion"], name="core_post_number__472f91_idx"
            ),
        ),
    ]
