# Generated by Django 5.1.1 on 2025-06-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_postmedia"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="postemotion",
            unique_together={("post", "user")},
        ),
    ]
