# Generated by Django 5.1.1 on 2025-06-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_postemotion_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postemotion",
            name="emotion",
        ),
    ]
